const $=s=>document.querySelector(s),board=$('#gameBoard'),message=$('#gameMessage'),coinCount=$('#coinCount'),scoreCount=$('#scoreCount'),moveCount=$('#moveCount'),timer=$('#timer'),bestScore=$('#bestScore'),bar=$('#progressBar'),win=$('#winOverlay'),summary=$('#winSummary');
const rows=5,cols=8,total=8;let player,coins,score,moves,started,tick,won;
const playerForm=$('#playerForm'),playerName=$('#playerName'),playerEmail=$('#playerEmail'),formMessage=$('#formMessage'),savedPlayers=$('#savedPlayers');
const getBest=()=>{try{return Number(localStorage.getItem('coin-quest-best')||0)}catch{return 0}},setBest=n=>{try{localStorage.setItem('coin-quest-best',n)}catch{}},time=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function getPlayers(){try{let data=JSON.parse(localStorage.getItem('coin-quest-players')||'[]');return Array.isArray(data)?data:[]}catch{return []}}
function renderPlayers(){let players=getPlayers();savedPlayers.innerHTML='';players.forEach((player,index)=>{let item=document.createElement('li'),name=document.createElement('strong');name.textContent=`${index+1}. ${player.name}`;item.append(name,` · ${player.email}`);savedPlayers.appendChild(item)});if(players.length)formMessage.textContent=`${players.length} de 3 registros guardados.`}
function loadPlayer(){let players=getPlayers();if(players.length){playerName.value=players[players.length-1].name;playerEmail.value=players[players.length-1].email}renderPlayers()}
playerForm.addEventListener('submit',e=>{e.preventDefault();let players=getPlayers();if(players.length>=3){formMessage.textContent='Ya tienes 3 registros guardados.';return}let data={name:playerName.value.trim(),email:playerEmail.value.trim()};try{players.push(data);localStorage.setItem('coin-quest-players',JSON.stringify(players));formMessage.textContent='Registro guardado correctamente.';playerForm.reset();renderPlayers()}catch{formMessage.textContent='No se pudieron guardar los datos.'}});loadPlayer();
function start(){player={r:4,c:0};coins=new Set;score=0;moves=0;started=null;won=false;while(coins.size<total){let r=Math.floor(Math.random()*rows),c=Math.floor(Math.random()*cols);if(r!==4||c!==0)coins.add(`${r}-${c}`)}clearInterval(tick);tick=setInterval(()=>{if(started&&!won)timer.textContent=time(Math.floor((Date.now()-started)/1000))},1000);timer.textContent='00:00';win.hidden=true;message.textContent='Usa las flechas, WASD o los controles para moverte.';render()}
function render(){let fragment=document.createDocumentFragment();board.innerHTML='';for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){let cell=document.createElement('div'),pos=`${r}-${c}`;cell.className='cell';cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`Fila ${r+1}, columna ${c+1}`);if(r===player.r&&c===player.c)cell.innerHTML='<span class="player-icon" aria-label="Jugador">M</span>';else if(coins.has(pos))cell.innerHTML='<span class="coin-icon" aria-label="Moneda"></span>';fragment.appendChild(cell)}board.appendChild(fragment);let got=total-coins.size;coinCount.textContent=got;scoreCount.textContent=score.toLocaleString('es-MX');moveCount.textContent=moves;bestScore.textContent=Math.max(score,getBest()).toLocaleString('es-MX');bar.style.width=`${got/total*100}%`}
function move(dir){if(won)return;let d={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]}[dir];if(!d)return;let r=player.r+d[0],c=player.c+d[1];if(r<0||r>=rows||c<0||c>=cols){message.textContent='¡Ese camino está bloqueado! Prueba otra dirección.';return}if(!started)started=Date.now();player={r,c};moves++;if(coins.delete(`${r}-${c}`)){score+=100;navigator.vibrate?.(35);let got=total-coins.size;message.textContent=got===total?'¡Todas las monedas conseguidas!':`¡Moneda conseguida! Faltan ${total-got}.`;if(got===total)finish()}else score=Math.max(0,score-1);render()}
function finish(){won=true;clearInterval(tick);let seconds=started?Math.floor((Date.now()-started)/1000):0;score+=Math.max(0,500-moves*5-seconds*2);let record=score>getBest();if(record)setBest(score);timer.textContent=time(seconds);summary.textContent=`${score.toLocaleString('es-MX')} puntos · ${moves} movimientos${record?' · ¡Nuevo récord!':''}`;setTimeout(()=>win.hidden=false,250)}
document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>move(b.dataset.direction));document.addEventListener('keydown',e=>{let d={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'}[e.key];if(d){e.preventDefault();move(d)}});$('#restartButton').onclick=start;$('#playAgainButton').onclick=start;start();
function connection(){let online=navigator.onLine,s=$('#connectionStatus');s.classList.toggle('offline',!online);s.lastChild.textContent=online?' En línea':' Sin conexión'}addEventListener('online',connection);addEventListener('offline',connection);connection();let prompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(prompt){prompt.prompt();await prompt.userChoice;prompt=null;$('#installButton').hidden=true}};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
